adapt_sd: true
adapt_sv: true
adapt_wh: true
batch_ms: 100
centroid_momentum: 0.95
ch_map: null
ch_mask: null
compute_loss: true
contrast_fun: logcosh
contrast_scope: spike_based
cov_alpha: 0.1
debug: false
device: cpu
ema_alpha: 0.95
eps: 1.0e-07
ext_fact: 10
ext_mode: block
fifo_length: null
filter_order: 4
fs: 2048
highcut: 500.0
lowcut: 20.0
lr_mode: fixed
max_sigma_batches: 300
notch_n_harmonics: 3
notch_order: 2
notch_width_hz: 1.0
powerline: true
powerline_freq: 50.0
replace_bad_channels: false
safety_clip_multiplier_sv: 20.0
safety_clip_multiplier_wh: 20.0
save_params: false
shrinkage: 0.001
source_fifo_batches: 2
spike_det_exp: 2.0
spike_height_mult: 3
spike_min_dist_ms: 10
spike_prev_weight: 5
sv_epochs: 1
sv_learning_rate: 0.0024222252021885837
sv_tol: 0.0001
wh_learning_rate: 0.04038249056090869
wh_mode: kl_to_identity
wh_sv_coupling: true
