 # General parameters
fs: 2048
device: null

# Preprocessing parameters
lowcut: 20.0
highcut: 500.0
powerline: True
powerline_freq: 50.0

# Decomposition parameters
ext_fact: 10

# Decomposition adaptation
batch_ms: 100
adapt_wh: True
adapt_sv: True
adapt_sd: True
compute_loss: True

# Learning rates
wh_learning_rate: 1.0e-3
sv_learning_rate: 5.0e-4

# Source separation parameters
sv_epochs: 1
sv_tol: 1.0e-4
contrast_fun: logcosh

# Whitening parameters
cov_reg_eps: 1e-6

# Spike detection parameters
spike_height_mult: 3
spike_prev_weight: 5
spike_dist_ms: 10

# Adaptation hyperparameters
wh_mode: kl_to_identity   # "kl_to_identity" or "kl_to_cal"
shrinkage: 1.0e-3
eps: 1.0e-7
max_rel_delta_v: 5.0e-3
max_rel_delta_b: 1.0e-3
min_spikes_for_update: 1
orthonormalization: qr
contrast_scope: batch_based
peak_power: 2.0
strict_peaks: true
use_abs_for_detection: true
fifo_length: 0
source_fifo_batches: 2
centroid_momentum: 0.95
min_spikes_for_centroid: 1
min_base_peaks_for_centroid: 3
debug: false